name = "Music Player"
author = "ScottyThePilot"
prefix = "sct_jukebox"
mainprefix = "x"

[version]
git_hash = 0

[files]
exclude = [
  "**/ace_actions_jukebox_vehicle.hpp",
  "**/ace_actions_jukebox.hpp",
  "**/CfgVehicles.hpp",
  "**/CfgWeapons.hpp",
]

[hemtt.release]
sign = true
archive = false
